In [1]:
import pandas as pd
import numpy as np

## Creating a Series from a List

In [2]:
my_list = ['Apple', 'Banana', 'Cherry']

In [3]:
my_series = pd.Series(my_list)

In [4]:
print(my_series)

0     Apple
1    Banana
2    Cherry
dtype: object


## Creating a Series from an Array

In [5]:
my_array = np.array([10, 20, 30, 40, 50])

In [6]:
series_from_array = pd.Series(my_array)

In [7]:
print(series_from_array)

0    10
1    20
2    30
3    40
4    50
dtype: int64


## Creating a Series from a Dictionary

In [8]:
my_dict = {
    'Name': 'Alice',
    'Age': 25,
    'Occupation': 'Engineer'
}

In [9]:
my_series = pd.Series(my_dict)

In [10]:
print(my_series)

Name             Alice
Age                 25
Occupation    Engineer
dtype: object


## Creating a Series from a Tuple

In [11]:
my_tuple = ('Apple', 'Banana', 'Cherry')

In [12]:
my_series = pd.Series(my_tuple)

In [13]:
print(my_series)

0     Apple
1    Banana
2    Cherry
dtype: object


## Creating a Series from a CSV file

In [15]:
df = pd.read_csv('housing.csv')

In [16]:
series = df['Rooms']

In [17]:
series.head()

0    2
1    2
2    3
3    3
4    4
Name: Rooms, dtype: int64

In [18]:
series = df.iloc[:, 2]

In [19]:
series.head()

0    2
1    2
2    3
3    3
4    4
Name: Rooms, dtype: int64

## Creating Custom Index Labels

In [20]:
data = [10, 20, 30, 40]
index = ['A', 'B', 'C', 'D']

series = pd.Series(data, index=index)

In [21]:
print(series)

A    10
B    20
C    30
D    40
dtype: int64


## Utilizing Custom Index Labels

In [22]:
print(series['A'])
print(series['B'])

10
20


In [23]:
prices = [100.50, 102.20, 98.75, 101.80, 99.45]
dates = ['2023-06-20', '2023-06-21', '2023-06-22', '2023-06-23', '2023-06-24']

stocks = pd.Series(prices, index=pd.to_datetime(dates))

In [24]:
stocks

2023-06-20    100.50
2023-06-21    102.20
2023-06-22     98.75
2023-06-23    101.80
2023-06-24     99.45
dtype: float64

In [25]:
print(stocks['2023-06-20'])

100.5


## Assigning a Name to a Series

In [26]:
series = pd.Series([10, 20, 30, 40], name='MySeries')

In [27]:
series

0    10
1    20
2    30
3    40
Name: MySeries, dtype: int64

In [28]:
series = pd.Series([10, 20, 30, 40])
series.name = 'MySeries'
series

0    10
1    20
2    30
3    40
Name: MySeries, dtype: int64

## Analyzing Size, Shape, Uniqueness, and Value Counts in a Pandas Series

In [29]:
series = pd.Series([10, 20, 30, 40, 50])
size = len(series)
print('Size of the Series:', size)

Size of the Series: 5


In [30]:
shape = series.shape
print('Shape of the Series:', shape)

Shape of the Series: (5,)


## Uniqueness in a Series

In [31]:
series = pd.Series([10, 20, 30, 40, 50, 10, 20])

In [32]:
unique_values = series.unique()

In [33]:
unique_values

array([10, 20, 30, 40, 50])

In [34]:
print(unique_values)

[10 20 30 40 50]


In [35]:
type(unique_values)

numpy.ndarray

## Value Counts in a Series

In [36]:
series = pd.Series([10, 20, 30, 40, 50, 10, 20, 30, 20])

value_counts = series.value_counts()

In [37]:
value_counts

20    3
10    2
30    2
40    1
50    1
Name: count, dtype: int64

In [38]:
type(value_counts)

pandas.core.series.Series

In [39]:
value_counts.loc[20]

np.int64(3)

## Analyzing Data with Head, Tail and Sample

In [40]:
series = pd.Series([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

In [41]:
sample_data = series.sample()
sample_data

0    10
dtype: int64

In [42]:
sample_data = series.sample()
sample_data

0    10
dtype: int64

In [43]:
sample_data = series.sample()
sample_data

8    90
dtype: int64

In [44]:
sample_data = series.sample()
sample_data

6    70
dtype: int64

In [45]:
sample_data = series.sample(3)
sample_data

8    90
3    40
4    50
dtype: int64

In [46]:
type(sample_data)

pandas.core.series.Series

## Indexing and Selecting Data

In [47]:
s = pd.Series([1, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E'])

In [50]:
element = s['B']  # Label based indexing
element

np.int64(2)

In [51]:
s1 = pd.Series([10, 20, 30, 40, 50, 10, 20])

In [52]:
s1_e1 = s1[20]
s1_e1

KeyError: 20

In [54]:
s1_e2 = s1[1] # Position based indexing
s1_e2

np.int64(20)

In [55]:
subsets = s[[0, 2, 4]]
subsets

C:\Users\ZhangZhihui\AppData\Local\Temp\ipykernel_16952\1268492315.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  subsets = s[[0, 2, 4]]


A    1
C    3
E    5
dtype: int64

In [56]:
subsets = s.iloc[[0, 2, 4]]
subsets

A    1
C    3
E    5
dtype: int64

In [57]:
element = s.loc['B']
element

np.int64(2)

In [58]:
subset = s.loc[['A', 'C', 'E']]
subset

A    1
C    3
E    5
dtype: int64

## Arithmetic Operations in Series

In [59]:
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 9])
s3 = s1 + s2
s3

0     3
1     7
2    11
3    15
4    19
dtype: int64

In [60]:
s3 = s1 - s2
s3

0    1
1    1
2    1
3    1
4    1
dtype: int64

In [61]:
s3 = s1 * s2
s3

0     2
1    12
2    30
3    56
4    90
dtype: int64

In [62]:
s3 = s1 / s2
s3

0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [63]:
s3 = s1 % s2
s3

0    0
1    1
2    1
3    1
4    1
dtype: int64

## Arithmetic Operation with Non-Numerical Series

In [64]:
s1 = pd.Series(['a', 'b', 'c'])
s2 = pd.Series(['d', 'e', 'f'])

In [65]:
s3 = s1 + s2
s3

0    ad
1    be
2    cf
dtype: object

## Series with Different Indices

In [66]:
s1 = pd.Series([2, 4, 6], index=['a', 'b', 'c'])
s2 = pd.Series([1, 3, 5], index=['b', 'c', 'd'])

In [67]:
s3 = s1 + s2
s3

a    NaN
b    5.0
c    9.0
d    NaN
dtype: float64

## Implicit Type Conversion

In [68]:
s1 = pd.Series([2, 4, 6])
s2 = pd.Series([1.0, 2.0, 3.0])

In [69]:
s3 = s1 + s2
s3

0    3.0
1    6.0
2    9.0
dtype: float64

## Division by Zero

In [70]:
s1 = pd.Series([2.0, 4.0, 6.0])
s2 = pd.Series([0, 0, 0])

In [71]:
s3 = s1 / s2
s3

0    inf
1    inf
2    inf
dtype: float64

## Broadcastring in Series

In [72]:
s = pd.Series([1, 2, 3, 4, 5])

In [73]:
result = s + 1
result

0    2
1    3
2    4
3    5
4    6
dtype: int64

## Filtering Data with Series

In [74]:
s = pd.Series([10, 20, 30, 40, 50])

In [75]:
filtered_data = s[s > 30]
filtered_data

3    40
4    50
dtype: int64

In [76]:
s = pd.Series(['apple', 'banana', 'cherry', 'apple', 'kiwi'])

In [77]:
filtered_data = s[s == 'apple']
filtered_data

0    apple
3    apple
dtype: object

## Filtering Data Using Logical Operators

In [78]:
s = pd.Series([1, 5, 3, 9, 4])

In [79]:
filtered_data = s[(s > 2) & (s < 7)]

In [80]:
filtered_data

1    5
2    3
4    4
dtype: int64

In [81]:
filtered_data = s[~(s > 2)]
filtered_data

0    1
dtype: int64

In [82]:
s = pd.Series(['apple', 'banana', 'cherry', 'apple', 'kiwi', 'orange'])

In [83]:
filtered_data = s[(s == 'apple') | (s == 'banana')]
filtered_data

0     apple
1    banana
3     apple
dtype: object

## Filtering Data Using Methods

In [84]:
filtered_data = s[s.isin(['apple', 'kiwi', 'grape'])]
filtered_data

0    apple
3    apple
4     kiwi
dtype: object

In [85]:
s = pd.Series([1, 3, 5, 7, 9])

In [86]:
filtered_data = s[s.between(3, 7)]
filtered_data

1    3
2    5
3    7
dtype: int64

## NaN Values in Pandas Series

In [87]:
arr = np.array([1, 2, np.nan, 4, 5])

In [88]:
result_add = arr + 2
result_add

array([ 3.,  4., nan,  6.,  7.])

In [89]:
result_mul = arr * 2
result_mul

array([ 2.,  4., nan,  8., 10.])

In [90]:
s = pd.Series([1, 2, np.nan, 4, 5])

In [91]:
result_add = s + 2
result_add

0    3.0
1    4.0
2    NaN
3    6.0
4    7.0
dtype: float64

In [92]:
result_mul = s * 2
result_mul

0     2.0
1     4.0
2     NaN
3     8.0
4    10.0
dtype: float64

## Mean and Median Calculation Using NAN

In [93]:
mean_np = np.mean(arr)
mean_np

np.float64(nan)

In [94]:
median_np = np.median(arr)
median_np

np.float64(nan)

In [95]:
mean_pd = s.mean()
mean_pd

np.float64(3.0)

In [96]:
median_pd = s.median()
median_pd

np.float64(3.0)