In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.datasets import load_boston

ImportError: 
`load_boston` has been removed from scikit-learn since version 1.2.

The Boston housing prices dataset has an ethical problem: as
investigated in [1], the authors of this dataset engineered a
non-invertible variable "B" assuming that racial self-segregation had a
positive impact on house prices [2]. Furthermore the goal of the
research that led to the creation of this dataset was to study the
impact of air quality but it did not give adequate demonstration of the
validity of this assumption.

The scikit-learn maintainers therefore strongly discourage the use of
this dataset unless the purpose of the code is to study and educate
about ethical issues in data science and machine learning.

In this special case, you can fetch the dataset from the original
source::

    import pandas as pd
    import numpy as np

    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]

Alternative datasets include the California housing dataset and the
Ames housing dataset. You can load the datasets as follows::

    from sklearn.datasets import fetch_california_housing
    housing = fetch_california_housing()

for the California housing dataset and::

    from sklearn.datasets import fetch_openml
    housing = fetch_openml(name="house_prices", as_frame=True)

for the Ames housing dataset.

[1] M Carlisle.
"Racist data destruction?"
<https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8>

[2] Harrison Jr, David, and Daniel L. Rubinfeld.
"Hedonic housing prices and the demand for clean air."
Journal of environmental economics and management 5.1 (1978): 81-102.
<https://www.researchgate.net/publication/4974606_Hedonic_housing_prices_and_the_demand_for_clean_air>


In [2]:
data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep=r"\s+", skiprows=22, header=None)

In [3]:
raw_df

0      1      2    3      4      5     6       7    8      9   \
0       0.00632  18.00   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1     396.90000   4.98  24.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
2       0.02731   0.00   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
3     396.90000   9.14  21.60  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
4       0.02729   0.00   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
...         ...    ...    ...  ...    ...    ...   ...     ...  ...    ...   
1007  396.90000   5.64  23.90  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
1008    0.10959   0.00  11.93  0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
1009  393.45000   6.48  22.00  NaN    NaN    NaN   NaN     NaN  NaN    NaN   
1010    0.04741   0.00  11.93  0.0  0.573  6.030  80.8  2.5050  1.0  273.0   
1011  396.90000   7.88  11.90  NaN    NaN    NaN   NaN     NaN  NaN    NaN   

        10  
0     15.3  
1      NaN  
2     17.8  
3      NaN  
4     17.8  
...    ...  
1007   NaN  
1008  21.0  
1009   NaN  
1010  21.0  
1011   NaN  

[1012 rows x 11 columns]

In [4]:
print(raw_df.values[::2, :])

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.0000e+00 2.9600e+02 1.5300e+01]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 2.0000e+00 2.4200e+02 1.7800e+01]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 2.0000e+00 2.4200e+02 1.7800e+01]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 1.0000e+00 2.7300e+02 2.1000e+01]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 1.0000e+00 2.7300e+02 2.1000e+01]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 1.0000e+00 2.7300e+02 2.1000e+01]]


In [5]:
type(raw_df.values)

numpy.ndarray

In [6]:
print(raw_df.values[1::2, :2])

[[396.9    4.98]
 [396.9    9.14]
 [392.83   4.03]
 ...
 [396.9    5.64]
 [393.45   6.48]
 [396.9    7.88]]


In [7]:
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [9]:
df = pd.DataFrame(data, columns=['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT'])

In [10]:
df['MEDV'] = target

In [11]:
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

## Filtering by Logical Operators

In [12]:
filtered_by_chas = df[df['CHAS'] == 1]
filtered_by_chas.head()

CRIM   ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD    TAX  \
142  3.32105  0.0  19.58   1.0  0.871  5.403  100.0  1.3216  5.0  403.0   
152  1.12658  0.0  19.58   1.0  0.871  5.012   88.0  1.6102  5.0  403.0   
154  1.41385  0.0  19.58   1.0  0.871  6.129   96.0  1.7494  5.0  403.0   
155  3.53501  0.0  19.58   1.0  0.871  6.152   82.6  1.7455  5.0  403.0   
160  1.27346  0.0  19.58   1.0  0.605  6.250   92.6  1.7984  5.0  403.0   

     PTRATIO       B  LSTAT  MEDV  
142     14.7  396.90  26.82  13.4  
152     14.7  343.28  12.12  15.3  
154     14.7  321.02  15.12  17.0  
155     14.7   88.01  15.02  15.6  
160     14.7  338.92   5.50  27.0

In [13]:
filtered_greater_than = df[df['RM'] > 6]
filtered_greater_than.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [14]:
filtered_less_than = df[df['TAX'] < 300]
filtered_less_than.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [15]:
filtered_greater_equal = df[df['NOX'] >= 0.5]
filtered_greater_equal.head()

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575   65.2  4.0900  1.0  296.0   
6  0.08829  12.5   7.87   0.0  0.524  6.012   66.6  5.5605  5.0  311.0   
7  0.14455  12.5   7.87   0.0  0.524  6.172   96.1  5.9505  5.0  311.0   
8  0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821  5.0  311.0   
9  0.17004  12.5   7.87   0.0  0.524  6.004   85.9  6.5921  5.0  311.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
6     15.2  395.60  12.43  22.9  
7     15.2  396.90  19.15  27.1  
8     15.2  386.63  29.93  16.5  
9     15.2  386.71  17.10  18.9

In [16]:
filtered_and = df[(df['RM'] > 6) & (df['DIS'] <= 2.0)]
filtered_and.head()

CRIM   ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD    TAX  \
128  0.32543  0.0  21.89   0.0  0.624  6.431   98.8  1.8125  4.0  437.0   
137  0.35233  0.0  21.89   0.0  0.624  6.454   98.4  1.8498  4.0  437.0   
139  0.54452  0.0  21.89   0.0  0.624  6.151   97.9  1.6687  4.0  437.0   
140  0.29090  0.0  21.89   0.0  0.624  6.174   93.6  1.6119  4.0  437.0   
145  2.37934  0.0  19.58   0.0  0.871  6.130  100.0  1.4191  5.0  403.0   

     PTRATIO       B  LSTAT  MEDV  
128     21.2  396.90  15.39  18.0  
137     21.2  394.08  14.59  17.1  
139     21.2  396.90  18.46  17.8  
140     21.2  388.08  24.16  14.0  
145     14.7  172.91  27.80  13.8

In [17]:
filtered_or = df[(df['RM'] > 6) | (df['DIS'] <= 2.0)]
filtered_or.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [18]:
filtered_not = df[~(df['RM'] > 6)]
filtered_not.head()

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD    TAX  \
8   0.21124  12.5   7.87   0.0  0.524  5.631  100.0  6.0821  5.0  311.0   
12  0.09378  12.5   7.87   0.0  0.524  5.889   39.0  5.4509  5.0  311.0   
13  0.62976   0.0   8.14   0.0  0.538  5.949   61.8  4.7075  4.0  307.0   
15  0.62739   0.0   8.14   0.0  0.538  5.834   56.5  4.4986  4.0  307.0   
16  1.05393   0.0   8.14   0.0  0.538  5.935   29.3  4.4986  4.0  307.0   

    PTRATIO       B  LSTAT  MEDV  
8      15.2  386.63  29.93  16.5  
12     15.2  390.50  15.71  21.7  
13     21.0  396.90   8.26  20.4  
15     21.0  395.62   8.47  19.9  
16     21.0  386.85   6.58  23.1

## Filtering by Numeric Methods

In [19]:
filtered_query = df.query('RM > 6 and MEDV > 25')
filtered_query.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
5  0.02985   0.0   2.18   0.0  0.458  6.430  58.7  6.0622  3.0  222.0   
7  0.14455  12.5   7.87   0.0  0.524  6.172  96.1  5.9505  5.0  311.0   

   PTRATIO       B  LSTAT  MEDV  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2  
5     18.7  394.12   5.21  28.7  
7     15.2  396.90  19.15  27.1

In [20]:
filtered_between = df[df['TAX'].between(200, 400)]
filtered_between.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [21]:
filtered_isin_age = df[df['AGE'].isin([65.2, 90.0])]
filtered_isin_age.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900   1.0  296.0   
104  0.13960   0.0   8.56   0.0  0.520  6.167  90.0  2.4210   5.0  384.0   
119  0.14476   0.0  10.01   0.0  0.547  5.731  65.2  2.7592   6.0  432.0   
460  4.81213   0.0  18.10   0.0  0.713  6.701  90.0  2.5975  24.0  666.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
104     20.9  392.69  12.33  20.1  
119     17.8  391.50  13.61  19.3  
460     20.2  255.23  16.42  16.4

## Filtering by Where Condition

In [22]:
filtered_where = df.where(df['RM'] > 7)
filtered_where.head()

CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  PTRATIO  \
0      NaN  NaN    NaN   NaN    NaN    NaN   NaN     NaN  NaN    NaN      NaN   
1      NaN  NaN    NaN   NaN    NaN    NaN   NaN     NaN  NaN    NaN      NaN   
2  0.02729  0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0     17.8   
3      NaN  NaN    NaN   NaN    NaN    NaN   NaN     NaN  NaN    NaN      NaN   
4  0.06905  0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0     18.7   

        B  LSTAT  MEDV  
0     NaN    NaN   NaN  
1     NaN    NaN   NaN  
2  392.83   4.03  34.7  
3     NaN    NaN   NaN  
4  396.90   5.33  36.2

Remember that the where() method retains the original shape of the DataFrame and
replaces non-matching rows with NaN values. If you want to remove the rows where
the condition is not met, you can use the .dropna() method after applying .where():

In [23]:
filtered_where_notnull = filtered_where.dropna()
filtered_where_notnull.head()

CRIM    ZN  INDUS  CHAS     NOX     RM   AGE     DIS  RAD    TAX  \
2   0.02729   0.0   7.07   0.0  0.4690  7.185  61.1  4.9671  2.0  242.0   
4   0.06905   0.0   2.18   0.0  0.4580  7.147  54.2  6.0622  3.0  222.0   
40  0.03359  75.0   2.95   0.0  0.4280  7.024  15.8  5.4011  3.0  252.0   
55  0.01311  90.0   1.22   0.0  0.4030  7.249  21.9  8.6966  5.0  226.0   
64  0.01951  17.5   1.38   0.0  0.4161  7.104  59.5  9.2229  3.0  216.0   

    PTRATIO       B  LSTAT  MEDV  
2      17.8  392.83   4.03  34.7  
4      18.7  396.90   5.33  36.2  
40     18.3  395.62   1.98  34.9  
55     17.9  395.93   4.81  35.4  
64     18.6  393.24   8.05  33.0

## Filtering by Date and Time Methods

In [24]:
date_rng = pd.date_range(start='2023-01-01', end='2023-01-10', freq='D')
values = range(len(date_rng))
df = pd.DataFrame({'value': values}, index=date_rng)

In [25]:
df

value
2023-01-01      0
2023-01-02      1
2023-01-03      2
2023-01-04      3
2023-01-05      4
2023-01-06      5
2023-01-07      6
2023-01-08      7
2023-01-09      8
2023-01-10      9

In [26]:
filtered_date_index = df['2023-01-03':'2023-01-07']
filtered_date_index

value
2023-01-03      2
2023-01-04      3
2023-01-05      4
2023-01-06      5
2023-01-07      6

By using the syntax df[‘2023-01-03’:’2023-01-07’], we are extracting
a subset of the original DataFrame that includes rows corresponding to the dates
from January 3rd, 2023, to January 7th, 2023, **inclusive**.

In [27]:
filtered_loc = df.loc[df.index >= '2023-01-05']
filtered_loc

value
2023-01-05      4
2023-01-06      5
2023-01-07      6
2023-01-08      7
2023-01-09      8
2023-01-10      9

In [28]:
filtered_query = df.query('index >= "2023-01-06"')
filtered_query

value
2023-01-06      5
2023-01-07      6
2023-01-08      7
2023-01-09      8
2023-01-10      9

In [29]:
date_rng = pd.date_range(start='2023-01-01 08:00', periods=10, freq='H')
values = range(len(date_rng))
df = pd.DataFrame({'value': values}, index=date_rng)

C:\Users\ZhangZhihui\AppData\Local\Temp\ipykernel_20812\1907546445.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  date_rng = pd.date_range(start='2023-01-01 08:00', periods=10, freq='H')


In [30]:
date_rng = pd.date_range(start='2023-01-01 08:00', periods=10, freq='h')
values = range(len(date_rng))
df = pd.DataFrame({'value': values}, index=date_rng)

In [31]:
filtered_between_time = df.between_time('10:00', '16:00')
filtered_between_time

value
2023-01-01 10:00:00      2
2023-01-01 11:00:00      3
2023-01-01 12:00:00      4
2023-01-01 13:00:00      5
2023-01-01 14:00:00      6
2023-01-01 15:00:00      7
2023-01-01 16:00:00      8

## Filtering Null or Missing Values

In [32]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Math': [85, np.nan, 72, 90, 65],
    'English': [90, 78, np.nan, 85, 92]
}

df = pd.DataFrame(data)
df

Name  Math  English
0    Alice  85.0     90.0
1      Bob   NaN     78.0
2  Charlie  72.0      NaN
3    David  90.0     85.0
4      Eve  65.0     92.0

In [33]:
missing_scores_mask = df.isna()
missing_scores_mask

Name   Math  English
0  False  False    False
1  False   True    False
2  False  False     True
3  False  False    False
4  False  False    False

In [34]:
missing_scores_filtered = df[missing_scores_mask.any(axis=1)]
missing_scores_filtered

Name  Math  English
1      Bob   NaN     78.0
2  Charlie  72.0      NaN

In [35]:
non_missing_scores_mask = df.notna()
non_missing_scores_filtered = df[non_missing_scores_mask.all(axis=1)]
non_missing_scores_filtered

Name  Math  English
0  Alice  85.0     90.0
3  David  90.0     85.0
4    Eve  65.0     92.0